package com.psujek.dll;

public class PSCApiMethodCodes {
    static final int
            CONNECT_PRESENTATION_SPACE = 1,
            FIND_FIELD_LENGTH = 32,
            DISCONNECT_PRESENTATION_SPACE = 2,
            COPY_STRING_TO_FIELD = 33,
            SEND_KEY = 3,
            COPY_FIELD_TO_STRING = 34,
            WAIT = 4,
            SET_CURSOR_POSITION = 40,
            COPY_PRESENTATION_SPACE = 5,
            START_KEYSTROKE_INTERCEPT = 50,
            SEARCH_PRESENTATION_SPACE = 6,
            GET_KEY = 51,
            QUERY_CURSOR_LOCATION = 7,
            POST_INTERCEPT_STATUS = 52,
            COPY_PRESENTATION_SPACE_TO_STRING = 8,
            STOP_KEYSTROKE_INTERCEPT = 53,
            SET_SESSION_PARAMETERS = 9,
            SEND_FILE = 90,
            QUERY_SESSIONS = 10,
            RECEIVE_FILE = 91,
            COPY_OIA = 13,
            CONVERT_POSITION_OR_ROWCOL = 99,
            QUERY_FIELD_ATTRIBUTE = 14,
            CONNECT_WINDOW_SERVICES = 101,
            COPY_STRING_TO_PRESENTATION_SPACE = 15,
            DISCONNECT_WINDOW_SERVICES = 102,
            PAUSE = 18,
            QUERY_WINDOW_COORDINATES = 103,
            QUERY_SYSTEM = 20,
            WINDOW_STATUS = 104,
            RESET_SYSTEM = 21,
            QUERY_SESSIONS_FULL = 910,
            QUERY_SESSION_STATUS = 22,
            ASSOCIATE_PROFILE = 911,
            START_HOST_NOTIFICATION = 23,
            REMOVE_PROFILE = 912,
            QUERY_HOST_UPDATE = 24,
            GET_ASSOCIATIONS = 913,
            STOP_HOST_NOTIFICATION = 25,
            FIND_FILE_NAME = 914,
            SEARCH_FIELD = 30,
            FIND_SHORT_NAME = 915,
            FIND_FIELD_POSITION = 31;
}
